# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.2
  - 7.3
  - 7.4

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install

# Commands you want to run that will verify your build.
script: phpunit
